source("getM4.R")
source("metrics.R")

# computes the matrix of forecasting errors from the matrix of forecasts
# returns list with fields: (id, ts_train, ts_test, mat_forecast, perc_errors, sOWA)
compute_errors <- function(df) {
  methods <- c('arima', 'ets', 'nnetar', 'tbats', 'stlm', 'rw', 'theta', 'naive', 'snaive')
  m <- length(methods)
  for (i in 1:length(df)) {
    if (i %% 1000 == 0)
      print(i)
    # calculate percentage errors
    df[[i]]$perc_errors <- matrix(NA, nrow=m, ncol=ncol(df[[i]]$mat_forecast))
    rownames(df[[i]]$perc_errors) <- rownames(df[[i]]$mat_forecast)
    # calculate sOWA
    df[[i]]$sOWA <- matrix(NA, nrow=1, ncol=m)
    colnames(df[[i]]$sOWA) <- methods
    for (j in 1:m) {
      # percentage error
      perc <- 100*(as.numeric(df[[i]]$ts_test)-df[[i]]$mat_forecast[j, ])/(as.numeric(df[[i]]$ts_test))
      df[[i]]$perc_errors[j, ] <- perc
      # smape and smape_naive_2
      smape <- smape_cal(as.numeric(df[[i]]$ts_test), df[[i]]$mat_forecast[j, ])
      naive_2_forec <- naive_2(df[[i]]$ts_train, length(as.numeric(df[[i]]$ts_test)))
      smape_naive_2 <- smape_cal(as.numeric(df[[i]]$ts_test), as.numeric(naive_2_forec))
      # mase and mase_naive_2
      mase <- mase_cal(df[[i]]$ts_train, df[[i]]$ts_test, df[[i]]$mat_forecast[j, ])
      naive_2_forec <- naive_2(df[[i]]$ts_train, length(as.numeric(df[[i]]$ts_test)))
      mase_naive_2 <- mase_cal(df[[i]]$ts_train, df[[i]]$ts_test, naive_2_forec)
      # add sOWA
      df[[i]]$sOWA[1, j] <- sOWA_cal(smape, smape_naive_2, mase, mase_naive_2) 
    }
  }
  return (df)
}

compute_errors_single_series <- function(df, i) {
  methods <- c('arima', 'ets', 'nnetar', 'tbats', 'stlm', 'rw', 'theta', 'naive', 'snaive')
  m <- length(methods)
  # calculate percentage errors
  perc_errors <- matrix(NA, nrow=m, ncol=ncol(df[[i]]$mat_forecast))
  rownames(perc_errors) <- rownames(df[[i]]$mat_forecast)
  # calculate sOWA
  sOWA <- matrix(NA, nrow=1, ncol=m)
  colnames(sOWA) <- methods
  for (j in 1:m) {
      # percentage error
      perc <- 100*(as.numeric(df[[i]]$ts_test)-df[[i]]$mat_forecast[j, ])/(as.numeric(df[[i]]$ts_test))
      # smape and smape_naive_2
      smape <- smape_cal(as.numeric(df[[i]]$ts_test), df[[i]]$mat_forecast[j, ])
      naive_2_forec <- naive_2(df[[i]]$ts_train, length(as.numeric(df[[i]]$ts_test)))
      smape_naive_2 <- smape_cal(as.numeric(df[[i]]$ts_test), as.numeric(naive_2_forec))
      # mase and mase_naive_2
      mase <- mase_cal(df[[i]]$ts_train, df[[i]]$ts_test, df[[i]]$mat_forecast[j, ])
      print(smape_naive_2)
      naive_2_forec <- naive_2(df[[i]]$ts_train, length(as.numeric(df[[i]]$ts_test)))
      mase_naive_2 <- mase_cal(df[[i]]$ts_train, df[[i]]$ts_test, naive_2_forec)
      # add sOWA
      sOWA[1, j] <- sOWA_cal(smape, smape_naive_2, mase, mase_naive_2) 
  }
  return(sOWA)
  
}


# returns a new dataset with fields 'id', ts_train', 'ts_test', 'mat_forecast'
create_df <- function(f_series, t_series) {
  df <- mapply(function(mat_forecast, series_obj){
    lentry <- list()
    lentry$id <- series_obj$st
    lentry$ts_train <- series_obj$x
    lentry$ts_test <- series_obj$xx
    lentry$mat_forecast <- mat_forecast
    lentry
  }, f_series, t_series, SIMPLIFY = FALSE)
  return (df)
}


SERIES_TYPE = "yearly"

M4 <- readRDS(file="M4_val.rds")

if (SERIES_TYPE == "monthly") {
  df_series <- get_M4_monthly(M4)
} else if (SERIES_TYPE == "yearly") {
  df_series <- get_M4_yearly(M4)
} else if (SERIES_TYPE == "quarterly") {
  df_series <- get_M4_quarterly(M4)
}

print(length(df_series))
remove(M4)

# This .rds has been generated by running 'mainForecast.R'
f_series <- readRDS(paste0(paste0("forecast_val_", SERIES_TYPE), ".rds"))
df <- create_df(f_series, df_series)
df_errors <- compute_errors(df)

# Save the matrix of forecasting errors for each series
#saveRDS(df_errors, file=paste0(paste0("raw_labels_", SERIES_TYPE), ".rds"))